### PR TITLE
Allow to enter number of participants upon subscribe

### LINKED ISSUE #16: Number field 'Participants' per registration
Great extension. I 'miss' only one thing: A person could register for an event but also give the number of participants (for example for children). So, a number field 'Participants' per registration would be great, which is also considered for the calculation for the total number of participants.

### PR DESCRIPTION
**Pull request by qzminski**
Closes #16.

### CODE REVIEW

**Comment by Aybee** [comment]
Hello Kamil, shall I try the changes within our installation? If so, how should I install? Override in vendor for temporary testing or is it possible to install it with contao manager?

**Comment by qzminski** [comment]
@Aybee you should be able to install the dev version using Contao Manager. Simply open the packages view, edit the version to `dev-feature/number-of-participants@dev` and update the packages. Please make sure that you do have a backup of the database and you perform install on a test system.

More information on the feature itself can be found in the docs: https://github.com/codefog/contao-events_subscriptions/blob/feature/number-of-participants/docs/03-advanced.md#number-of-participants

**Comment by Aybee** [comment]
Hello Kamil, I've tested it now. I see the `input[type=number]` in the `event_list_subscribe.html5` template. But no matter what number I type in there it will not count more than 1.

Within the BE subscribers list I see `[Number of participants: 1]`

Am I missing something?

**Comment by qzminski** [comment]
I assume you enabled the appropriate checkbox in the calendar/event settings? Is it a guest or member subscription?

Also, what do you mean that you see `input[type=number]` in the `event_list_subscribe.html5` template? The input type is in fact generated inside the `eventsubscription_form.html5` template. 🤔

**Comment by Aybee** [comment]
Yes, enabled the checkbox. Only member subscription, no restriction to a group.

Bildschirmfoto am 2020-07-28 um 18 03 46

Will say I see the number input field in the FE as it should be.

Bildschirmfoto am 2020-07-28 um 18 08 14

**Comment by Aybee** [comment]
Ok, thank you. Now I see e.g. `[Number of participants: 3]`

But the number of participants does not take into account the max number of subscribers and waiting list subscribers.

**Example**:
max Subscribers - 6
max on Waitinglist - 5
subscriber A comes with 3 participants
subscriber B comes with 5 participants

It is not possible to come with 8 people as only 6 people can participate. 

And I think it is not nice if B subscribes for 5 participants and 2 of them will be put on the waiting list as there are only 6 free places. Also your error notice for free places doesn't take the waitinglist max number into account. I tried A with 3 participants and B with 10 participants and you are setting all 10 onto the waiting list.

There has to be a hint that it is not possible to subscribe for 5 participants if there are only 3 places left (6 minus 3 from subscriber A). Or simply block the input of an impossible value with the max attribute.

You also can use some attributes for the number input field. 
```html
<input type="number" min="1" max="[max-free-places]" step="1" ...
```
To break it down:
**Example**:
max Subscribers - 10
max on Waitinglist - 20

1. You should **not be able** to subscribe **more** than the **free places without the waiting list**. (use the max attribute for the input, value 1-10)
OR
2. You should **not be able** to subscribe **more** than the **free places inclusive the waiting list**. (use the max attribute for the input, value 1-30)

I think 2. is **not good** as it splits the family/friends into subscribed and waiting.

Also if there are only some places left on the waitinglist the subscriber should be clear about that there's no guarantee getting subscriptions for all his participants.

**At last nother try to simply break it down**:

If there are free places on the **subscribers list** the max attribute should prevent the input of a higher number than these free places. 1-10 places

If there are **only** free places on the **waiting list** the max attribute should prevent the input of a higher number than these free places. 1-20 places.

Sorry for so much words. Its not as easy.

**Comment by qzminski** [comment]
Every subscription record contains a number of participants now. That means if a user tries to subscribe to an event that has not enough slots, either his subscription would be rejected, or he would be put on the waiting list. For the latter, it does NOT mean that the X participants would be subscribed, and the rest would land on the waiting list. This would be logically incorrect because a basic unit is, in fact, the subscription record (which contains a number of participants as a volume) and not the single participant itself. That means you cannot divide a single subscription record into smaller chunks, aka the participants.

Following your example, if only 6 subscribers are allowed, and there are already 3 on the list, you can only further subscribe with 3 participants. If you try to subscribe with more, they ALL would be put on the waiting list. So if a 4 person family would like to subscribe, they would be ALL put on the waiting list.

If you want to go to a movie with 4 people and there are only 3 seats left, you wouldn't buy 3 seats and let the last person go for the next projection. You could join a waitlist, though, until there are 4 free slots available, and only then will you be able to go in a full team.

**Comment by qzminski** [comment]
@Aybee any feedback? :wink:

**Comment by Aybee** [comment]
Sorry for being late. I will call David today and ask about functionality in real life case.

**Comment by Aybee** [comment]
Seems okay so far. Thanks again.

A small bug was noticed:
The calendars subscriptions overview (green icon on the far right) doesn't take into account the numberOfParicipants.

I've also managed it to bring the numberOfParicipants into the notifications `##subscription_numberOfParticipants##`.

What I'm missing is: How to get the numberOfParicipants into the FE templates to show it with the subsribers list and waiting list:
```
Subscribers - Waiting List
John (3)    - Ben (2)
Jane (1)    - Chen (1)
```

**Comment by qzminski** [comment]
> The calendars subscriptions overview (green icon on the far right) doesn't take into account the numberOfParicipants.

I have updated the subscriptions overview.

> What I'm missing is: How to get the numberOfParicipants into the FE templates to show it with the subsribers list and waiting list:

Since cae50dc you can turn it on in the frontend module settings.

**Comment by qzminski** [comment]
@Aybee any news on this?

**Comment by Aybee** [comment]
I will do some tests the next weeks. If you like, I can give you a BE admin account for taxiboot installation. The next days I plan to update a similar page from the same customer. There I will test it again. I think you should merge it into the master branch.

And thank you for your good work 🥇

**Pull request closed without merging**
