### PR TITLE
Update eventsubscription_form.html5

### PR DESCRIPTION
**Pull request by Aybee**
As I get a warning with Contao Debug Mode in FE and therefore can't see the content of the page anymore.

### CODE REVIEW

**Comment by Kahmoon** [comment]
Whats this change about?

**Comment by qzminski** [comment]
This can happen only in the module that is not a part of this extension, e.g. genuine event list module. Am I right? 🤔

**Comment by Aybee** [comment]
Mmh, I don't know. I can no longer force the error. I think it was, that `$this->subscriptionTypes` was not a variable at all or was no array. So the `foreach` fails.

**Comment by qzminski** [comment]
Exactly and that could probably only happen if you chose a frontend module that is not a part of this extension and adds no necessary data to the template. I will keep this open for now, as I am not sure if it should be merged 🤔

**Comment by Aybee** [comment]
Maybe you can close this one and I come back if it happens again. Then I can show you the stack trace of the warning in debug mode.

**Pull request closed without merging**
